language: python

python:
    - "3.6"

# Use container-based infrastructure for quicker build start-up
sudo: false

script:
    - python3 --version
    - ./pre-commit  # checking nvchecker.ini

matrix:
    fast_finish: true
